config/routes.rb
CarsWeb::Application.routes.draw do
  devise_for :users

  resources :cars do
    collection do
      delete 'destroy_multiple'
      delete 'clear_list_cars_cache_by_request'
    end
  end

  root to: 'cars#index'

end

app/models/car.rb
class Car < ActiveRecord::Base
  #attr_accessible :color, :horsepower, :name, :user

  # ASSOCIATIONS
  belongs_to :user

  # SCOPES
  scope :owned_by_user, -> (user) { includes(:user).references(:user).
                                where("users.id = ?", user.id)}

  scope :owned_by_female, -> {includes(:user).references(:user).
                              where("users.gender_cd = ?", 1)}
end

app/models/user.rb
class User < ActiveRecord::Base
  as_enum :gender, male: 0, female: 1
  after_initialize :set_default_gender, :if => :new_record?

  def set_default_gender
  	self.gender ||= :male
  end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :authentication_keys => [:login]

  # Setup accessible (or protected) attributes for your model
  #attr_accessible :name, :email, :login, :gender, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body

  # ASSOCIATIONS
  has_many :cars

  # VALIDATIONS
  validates_presence_of :password, on: :create
  validates_length_of :password, minimum: 8, if: :password
  validates_confirmation_of :password, if: :password

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 50 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  
  validates :login, presence: true, uniqueness: { case_sensitive: false }, format: { with: /\A[a-zA-Z0-9]+\Z/ },
               length: { minimum:1, maximum: 30 }
  validates :name, presence: true, length: {minimum: 1, maximum: 30}



end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  before_filter :clear_cars_list_cache


  def clear_cars_list_cache
    if devise_controller?
      Rails.cache.clear 'all_cars'
    end
  end
  
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  before_filter :set_car, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!, only: [:new, :create, :update]
  before_filter :is_owner? , only: [:edit, :update]
  after_filter :clear_list_cars_cache, only:[:update, :destroy_multiple, :destroy, :create]
  respond_to :html

  def index
    if user_signed_in? #If user signed in, just list all cars owned by current user
      @cars = Car.owned_by_user(current_user).order('cars.name ASC')
    
    else
      @cars = Car.order('cars.name ASC') unless fragment_exist?('all_cars')

      # Cars with at least 200 horsepowers
      @cars_200 = Car.where('horsepower >= ?', 200).order('cars.name ASC')
      
      #grey cars with at least 200 horsepowers and owned by woman
      @cars_grey_200_female = Car.owned_by_female.where('cars.horsepower >= ? and lower(cars.color) = ?', 200, 'grey').order('cars.name ASC')
      
    end
    respond_with @cars do |format|
      format.xml { render :layout => false, :text => @cars.to_xml }
      format.html
    end
  end

  def show
    respond_with(@car)
  end

  def new
    @car = Car.new
    respond_with(@car)
  end

  def edit
  end

  def create
    @car = Car.new(params[:car].merge(:user => current_user))
    @car.save
    respond_with(@car)
  end

  def update
    @car.update_attributes(params[:car])
    respond_with(@car)
  end

  def destroy
    @car.destroy
    respond_with(@car)
  end

  def destroy_multiple
    if params[:cars_list].present?
      Car.destroy(params[:cars_list])
      redirect_to cars_path, notice: 'Delete selected successfully!'
    else
      redirect_to cars_path, alert: 'You have to select at lease one car to delete.'
    end
    
  end

  def clear_list_cars_cache_by_request #When user press reload button
    if user_signed_in?
      redirect_to cars_path, alert: 'This available on guest only, :))'
    else
      Rails.cache.clear 'all_cars'
      # Query again to get cars list
      @cars = Car.order('cars.name ASC')
      respond_to do |format|
        format.js
      end
    end
  end

  private
    def set_car
      @car = Car.find(params[:id])
    end

    def clear_list_cars_cache
      Rails.cache.clear 'all_cars'
    end

    def is_owner?
      redirect_to car_path(@car) ,alert: 'You can only edit your own car.' unless @car.user == current_user
    end

end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  before_filter :configure_permitted_parameters

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up).push(:name, :email, :gender)
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:email, :gender, :password, :password_confirmation, :current_password) }
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/views/cars/_cars_table.html.haml
%table.table.table-striped#cars_list_table
  %thead
    %tr
      %th Name
      %th Color
      %th Horsepowers
      
  %tbody
    - cars.each do |car|
      %tr
        %td= link_to car.name, car_path(car)
        %td= car.color
        %td= car.horsepower

app/views/cars/_cars_table_with_options.html.haml
%table.table.table-striped#cars_list_table
  %thead
    %tr
      %th Name
      %th Color
      %th Horsepowers
      %th
        %input#checkall{type: "checkbox"}
      %th
        =t '.actions', :default => t("helpers.actions" + ":")
        = submit_tag "Delete selected", :class => 'btn btn-mini btn-danger', id: 'delete_multiple'
        = link_to 'XML', cars_path(:format => 'xml'), :class => 'btn btn-mini btn-info'
        = link_to 'Reload', clear_list_cars_cache_by_request_cars_path, :method => :delete, remote: true, class: 'btn btn-mini btn-primary' unless user_signed_in?
  %tbody
    - cache('all_cars', :expires_in => 5.minutes) do
      - cars.each do |car|
        %tr
          %td= link_to car.name, car_path(car)
          %td= car.color
          %td= car.horsepower
          %td= check_box_tag "cars_list[]", car.id
          %td
            = link_to t('.edit', :default => t("helpers.links.edit")), edit_car_path(car), :class => 'btn btn-mini'

app/views/cars/_form.html.haml
= simple_form_for @car, :html => { :class => 'form-horizontal' } do |f|
  = f.input :name
  = f.input :color
  = f.input :horsepower
  %br
  .form-actions
    = f.button :submit, :class => 'btn-primary'
    = link_to t('.cancel', :default => t("helpers.links.cancel")), cars_path, :class => 'btn btn-default'

app/views/cars/edit.html.haml
- model_class = Car
.page-header
  %h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/cars/index.html.haml
- model_class = Car
.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize.titleize

%h3 All cars
= form_tag destroy_multiple_cars_path, method: :delete do 
  %div#all_cars_list
    = render partial: 'cars_table_with_options', locals: {:cars => @cars}, cache: true
            
= link_to t('.new', :default => t("helpers.links.new")), new_car_path, :class => 'btn btn-primary'

- unless user_signed_in?
  %h3 List cars has at least 200HP
  = render partial: 'cars_table', locals: {:cars => @cars_200}
  
  %h3 List cars which has at least 200HP with grey color add by woman
  = render partial: 'cars_table', locals: {:cars => @cars_grey_200_female}
  

app/views/cars/new.html.haml
- model_class = Car
.page-header
  %h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/cars/show.html.haml
- model_class = Car
.page-header
  %h1=t '.title', :default => model_class.model_name.human.titleize

%p
  %strong= model_class.human_attribute_name(:name) + ':'
  %br
  = @car.name
%p
  %strong= model_class.human_attribute_name(:color) + ':'
  %br
  = @car.color
%p
  %strong= model_class.human_attribute_name(:horsepower) + ':'
  %br
  = @car.horsepower

.form-actions
  = link_to t('.back', :default => t("helpers.links.back")), cars_path, :class => 'btn btn-default'
  = link_to t('.edit', :default => t("helpers.links.edit")), edit_car_path(@car), :class => 'btn btn-default'
  = link_to t('.destroy', :default => t("helpers.links.destroy")), car_path(@car), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'

app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "CarsWeb"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"
    = stylesheet_link_tag "application", :media => "all"
    = favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144'
    = favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'
    = favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'
    = favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
    = favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'
    = javascript_include_tag "application"


  %body
    .navbar.navbar-default.navbar-fixed-top
      .container
        %button.navbar-toggle(type="button" data-toggle="collapse" data-target=".navbar-responsive-collapse")
          %span.icon-bar
          %span.icon-bar
          %span.icon-bar
        %a.navbar-brand(href="#{root_path}") CarsWeb
        .navbar-collapse.collapse.navbar-responsive-collapse
          %ul.nav.navbar-nav.pull-right
            = render 'layouts/menu/login_items'
            = render 'layouts/menu/registration_items'

    .container

      .row
        = bootstrap_flash
        = yield
    
      %footer
        %p &copy; Company 2015

app/views/layouts/menu/_login_items.html.haml
- if user_signed_in?
	%li 
		= link_to 'Logout', destroy_user_session_path, :method => :delete
- else
	%li 
		= link_to 'Login', new_user_session_path

app/views/layouts/menu/_registration_items.html.haml
- if user_signed_in?
	%li
		= link_to 'Edit profile', edit_user_registration_path
- else
	%li
		= link_to 'Register', new_user_registration_path